### ISSUE TITLE
Switch from CVE to DWF

### ISSUE THREAD

**Issue by todb-r7** [distributedweaknessfiling/dwf-request#36]
The pull requests listed below across the three repos for the Distributed Weakness Filing project all envision the same change: Generating identifiers formatted like `DWF-YYYY-NNN...` rather than `CVE-YYYY-NNN...`. This will disambiguate vulnerability identifiers sourced from the DWF project from those produced by the federation of [CVE Numbering Authorities](https://cve.mitre.org/cve/cna.html), and avoid any confusion in downstream users of these identifiers.

Since it's impossible to have one pull request cover several different repos, I've opened this issue to enable consolidated conversation. This issue should be marked as resolved when these pull requests are closed.

Finally, in the interest of full disclosure, I will note here that I'm member of the [CVE Board](https://cve.mitre.org/community/board/index.html).

**Pull requests**

Fixes to dwflist: distributedweaknessfiling/dwflist#15
Fixes to dwf-workflow: distributedweaknessfiling/dwf-workflow#13
Fixes to dwf-request: distributedweaknessfiling/dwf-request#35

**Comment by kurtseifried** [comment]
As per https://github.com/distributedweaknessfiling/dwf-workflow/issues/10#issuecomment-794686350 

I think defining acronyms is a fair point. I'll fix up some docs in the near future to do that.

But as for the naming, that's a no.
CVE now means "vulnerability" in the same way tissue is a kleenex.
If we create a "new" naming scheme we end up with
https://xkcd.com/927/
But if we reuse an existing naming scheme, there isn't an increase in identifier names.

We have staked out a claim well outside a range that could possibly be a concern, that's why the 1 million. It's a huge number that probably won't have any collisions (possibly ever, but at least for decades).

**Comment by todb-r7** [comment]
I guess I just don't understand why the DWF wants to simultaneously piggyback on the CVE namespace but also eschew the federation of [CVE numbering authorities](https://cve.mitre.org/cve/cna.html). If this open and transparent approach to identifier assignment is better, why not differentiate on that?

IOW, I am all for competition and complementation in this space, but I'd rather avoid downstream confusion.

**Comment by zmanion** [comment]
"CVE" as used for "providing information in the field of computer security via global computer network" looks like a trademark:

https://uspto.report/TM/76295592

https://uspto.report/TM/88932726

**Comment by kurtseifried** [comment]
The CVE Logo is indeed trademarked but we are very explicitly not using the CVE Logo. As such this trademark issue isn't a problem, thanks for your concern.
